typedef enum {
    MQTT_SN_CONNACK_ACCEPTED,
} mqtt_sn_connack_t;

typedef enum {
    MQTT_SN_TOPIC_TYPE_NORMAL,
    MQTT_SN_TOPIC_TYPE_PREDEFINED,
    MQTT_SN_TOPIC_TYPE_SHORT
} mqtt_sn_topic_type_t;

typedef enum {
    MQTT_SN_MESSAGE_TYPE_ADVERTISE,
    MQTT_SN_MESSAGE_TYPE_SEARCHGW,
    MQTT_SN_MESSAGE_TYPE_GWINFO,
    MQTT_SN_MESSAGE_TYPE_DNU1,
    MQTT_SN_MESSAGE_TYPE_CONNECT,
    MQTT_SN_MESSAGE_TYPE_CONNACK,
    MQTT_SN_MESSAGE_TYPE_WILLTOPICREQ,
    MQTT_SN_MESSAGE_TYPE_WILLTOPIC,
    MQTT_SN_MESSAGE_TYPE_WILLMSGREQ,
    MQTT_SN_MESSAGE_TYPE_WILLMSG,
    MQTT_SN_MESSAGE_TYPE_REGISTER,
    MQTT_SN_MESSAGE_TYPE_REGACK,
    MQTT_SN_MESSAGE_TYPE_PUBLISH,
    MQTT_SN_MESSAGE_TYPE_PUBACK,
    MQTT_SN_MESSAGE_TYPE_PUBCOMP,
    MQTT_SN_MESSAGE_TYPE_PUBREC,
    MQTT_SN_MESSAGE_TYPE_PUBREL,
    MQTT_SN_MESSAGE_TYPE_DNU2,
    MQTT_SN_MESSAGE_TYPE_SUBSCRIBE,
    MQTT_SN_MESSAGE_TYPE_SUBACK,
    MQTT_SN_MESSAGE_TYPE_UNSUBSCRIBE,
    MQTT_SN_MESSAGE_TYPE_UNSUBACK,
    MQTT_SN_MESSAGE_TYPE_PINGREQ,
    MQTT_SN_MESSAGE_TYPE_PINGRESP,
    MQTT_SN_MESSAGE_TYPE_DISCONNECT
} mqtt_sn_message_type_t;


#define MQTT_SN_QOS_NO_CONNECT 3
#define MQTT_SN_QOS_ONCE 0
#define MQTT_SN_QOS 1

#define MQTT_SN_PUBLISH_QOS 1
#define MQTT_SN_PUBLISH_TOPIC_TYPE 0

#define MQTT_SN_PUBLISH_HEADER_LENGTH 7


#define MQTT_SN_MESSAGE_ERROR 110
#define MQTT_SN_MESSAGE_HELLO 120
#define MQTT_SN_MESSAGE_PING 130
#define MQTT_SN_MESSAGE_MODE 140
#define MQTT_SN_MESSAGE_POWER 150
