foreground=yes
pid=

[aws-iot]
client = yes
accept=127.0.0.1:11883
connect=$IOT_HOST:8883
cert=certificate.pem.crt
key=private.pem.key
sslVersion = TLSv1.3
debug=7
requireCert=yes
verifyPeer=yes
verify=1
CAfile=AmazonRootCA1.pem
